### ISSUE TITLE
Week 2 - Requirement Elicitation

### ISSUE THREAD

**Issue by bengibaykal** [bengibaykal/swe574group1#10]
Software requirements will be extracted to be able to receive feedback from customer.

**Comment by bengibaykal** [comment]
Will be discussed in the meeting :

1.  User shall create and share posts.
2. User shall comment on posts.
3. User shall flag inappropriate posts.
4. User shall update the post status.
5. User shall create specific data types under communities.
6. User shall search within posts semantically.
7. User shall have summary report for posts.
8. User shall add semantic tags to posts.
9. User shall extract post as audio.
10. User shall subscribe to both posts and type of the posts.
11. User shall receive notification when subscribed to post or type of post.
12. Posts shall be semantically structured.
13. Posts shall have status feature.
14. Posts shall be extracted as audio.

**Comment by TuracAbb** [comment]
Requirement elicitation proposal, will be discussed in the meeting.

1. User should be able to register to the system with name, surname and unique email, password, username
2. User should be able to login to the system with email or username and password
3. User should be able to create post
4. User should be able to create generic community data types with entering title and description only (post type)
5. User should be able to create specific community data types with entering specific types such as location, URL, image, media and text
6. User should be able to add posts to community datatypes
7. User should be able to add comment to the posts
8. User should be able to add audio annotation to the post
9. User should be able to subscribe a post
10. User should be able to be notified about subscribed post when a new comment added
11. User should be able to be notified about subscribed post when post edited
12. User should be able to be notified about subscribed post when other people subscribed the post
13. User should be able to subscribe a data type (post type)
14. User should be able to be notified about subscribed data type when a new post added to the data type
15. User should be able to be notified about subscribed data type when post edited

**Comment by bengibaykal** [comment]
Questions:
1. Semantic tag is just from Wiki or custom tag will be used?

**Comment by jrqc** [comment]
•	User should be able to create community specific data types
•	User can search/join communities
•	User should be able to create/update posts/reports
•	Posts/Reports should be enhanced with external data
•	User should be able to comment on posts/reports
•	User can subscribe to specific posts
•	Inappropriate posts can be flagged
•	Posts/Reports must have type and description
•	Advanced search for posts/reports
•	Summary reports of posts?
•	Semantic tags?
