### ISSUE TITLE
Weekly Personal Effort Documentation 2nd Week 19.02.2020

### ISSUE THREAD

**Issue by bengibaykal** [bengibaykal/swe574group1#11]
Each team member will document personal effort for each week.
Deadline : 24.02.2020.

Format :
Task :
Duration :
Type of work :

**Comment by TuracAbb** [comment]
Task : Requirement Elicitation, React Framework
Duration : 5 hours
Type of work: Elicitate requirements, Watch tutorial and practice React

**Comment by bengibaykal** [comment]
Task : Requirement Elicitation, Research about W3C Annotation, REST Framework
Duration : 5 hours 
Type of work : Research

**Comment by eermis1** [comment]
Task : Requirement Elicitation, Research about W3C Activity Stream, REST Framework, JSON-LD
Duration : 6.5 hours
Type of work : Research

**Comment by jrqc** [comment]
Task – GitHub repo updated 
Duration : 60 min
Type of work : Modification

Task – Activity Stream/React Research
Duration : 60 min
Type of work : Research
