### ISSUE TITLE
Week 2 - Technical research - activity stream

### ISSUE THREAD

**Issue by TuracAbb** [bengibaykal/swe574group1#12]
For understanding requirements better, activity stream' s technical side will be investigated.

**Comment by eermis1** [comment]
The available Django Libraries are; 

1. django-stream 
pip install django-stream
The documents are available on [library web page](https://pypi.org/project/stream-django/) and [library github repo](https://github.com/GetStream/stream-django)

2. django-activity-stream 
pip install django-activity-stream
The documents are available on [library web page](https://django-activity-stream.readthedocs.io/en/latest/installation.html) and [library github repo](https://github.com/justquick/django-activity-stream)

Next Steps:
1. For each library pros and cons will be studied. 
2. The most appropriate will be determined.

**Comment by eermis1** [comment]
Latest status has been added to project wiki 

Task : Investigate activity stream frameworks in django 
Duration : 3 hours
