### ISSUE TITLE
Week 2 - Technical research - annotation

### ISSUE THREAD

**Issue by TuracAbb** [bengibaykal/swe574group1#13]
For understanding requirements better, annotations technical side will be investigated.

**Comment by bengibaykal** [comment]
I am sharing some of my research as draft.

Annnotation is set of connected resources typically has body and target.

Tagging is the simplest for of annotation:
1. Plain text tags
2. Semantic tags
* Tagging with URI
* Tagging with document

On github:
* JSONLD processor in python [https://github.com/digitalbazaar/pyld](url)
* JSONLD parser and serializer [https://github.com/RDFLib/rdflib-jsonld](url)

Django
F() expressions :
An F() object represents the value of a model field or annotated column. It makes it possible to refer to model field values and perform database operations using them without actually having to pull them out of the database into Python memory.

The Web Annotation Playground is a web-based Web Annotation viewer and debugger. If you are interested in learning to use Web Annotations, this tool will be of great help to you. Developers may also use the tool to debug, visualize, and share their Web Annotation content, in JSON-LD or HTML.
Playground:
[http://webannotation.org/playground/](url)

**Comment by bengibaykal** [comment]
DJANGO Rest Framework Annotations Example : [https://piratelearner.com/en/C/course/computer-science/django/annotations-tutorial-doing-it-with-django-rest-framework/22/](url)
