### ISSUE TITLE
Week 3 - Mockup Standard Decision

### ISSUE THREAD

**Issue by bengibaykal** [bengibaykal/swe574group1#19]
1. Mockup suggestions will be collected.
2. Best mockup standard and tool will be chosen.
Note : All mockups could be implemented with the application or style will be used.

**Comment by bengibaykal** [comment]
Suggestions:
1. [Balsamiq](https://balsamiq.com/)
Pros:
1. Add contributors & team members
2. Notes could be added
3. On cloud, collaborative editing option
4. Easy to use & share [Try my demo](https://balsamiq.cloud/sxkp8u6/p4vud6m)
Cons:
1. Too much advanced
2. User should get used to it.

[New Project (1).pdf](https://github.com/bengibaykal/swe574group1/files/4251380/New.Project.1.pdf)

**Comment by bengibaykal** [comment]
Suggestions:
1. [Balsamiq](https://balsamiq.com/)
Pros:
1. Add contributors & team members
2. Notes could be added
3. On cloud, collaborative editing option
4. Easy to use & share [Try my demo](https://balsamiq.cloud/sxkp8u6/p4vud6m)
Cons:
1. Too much advanced
2. User should get used to it.

**Comment by bengibaykal** [comment]
Suggestions:
1. [Balsamiq](https://balsamiq.com/)
Pros:
1. Add contributors & team members
2. Notes could be added
3. On cloud, collaborative editing option
4. Easy to use & share [Try my demo](https://balsamiq.cloud/sxkp8u6/p4vud6m)
Cons:
1. Too much advanced
2. User should get used to it.

[New Project (1).pdf](https://github.com/bengibaykal/swe574group1/files/4251380/New.Project.1.pdf)

**Comment by TuracAbb** [comment]
Suggestions:

**LucidChart**. https://www.lucidchart.com/
Online and free for boun mail
Can share work easily
Download work easily
User friendly GUI 
<img width="788" alt="Screen Shot 2020-02-25 at 9 44 51 PM" src="https://user-images.githubusercontent.com/55947787/75277047-5bc02580-5818-11ea-874a-4da1ec6fda24.png">

**Comment by bengibaykal** [comment]
**moqups.com**
Pros:
Easy to use, design is very nice.
Cons:
It has a object quota.

![image](https://user-images.githubusercontent.com/3228918/75285660-14da2c00-5828-11ea-89f2-3959148df57d.png)

![image](https://user-images.githubusercontent.com/3228918/75285700-2a4f5600-5828-11ea-97e8-48f87f763b08.png)

**Comment by bengibaykal** [comment]
Balsamiq will be the mock tool as decided by the team.
