### ISSUE TITLE
Week 3 - Version 2 Mockups

### ISSUE THREAD

**Issue by bengibaykal** [bengibaykal/swe574group1#21]
1. Search
2. Comment
3. Annotation
4. Inappropriate flag
5. Semantic Search & Semantic tagging
6. Advanced Search
7. Posts must support typical web types (json-ld)
8. Allow users to create audio versions of posts
9. Subsribing
10. Status

**Comment by TuracAbb** [comment]
11. General View of Community page includes subscribing (No:9) and flagging (No: 4).
