### ISSUE TITLE
Week 6 Class Diagram - Sequence Diagram Update

### ISSUE THREAD

**Issue by bengibaykal** [bengibaykal/swe574group1#34]
After the feedback meeting with Suzan Üsküdarlı , diagrams will be updated according to the relations within classes and methods.

**Comment by TuracAbb** [comment]
Creating Post, Creating Community and Creating new City UML sequence diagrams updated based on feedback and meeting 6 decisions.

**Comment by eermis1** [comment]
Use Case diagram and class diagram have been updated according to instructor feedbacks and meeting 6 team decisions
