### ISSUE TITLE
Weekly Personal Effort Documentation 1st Week

### ISSUE THREAD

**Issue by bengibaykal** [bengibaykal/swe574group1#4]
Each team member will document personal effort for each week.
Deadline : 17.02.2020.

Format :  
Task : 
Duration : 
Type of work :

**Comment by TuracAbb** [comment]
Task : Research Of Web Data Annotation
Duration : 2.5 hours
Type of work : Research

**Comment by jrqc** [comment]
Task : Wikidata Research
Duration : 80min
Type of work : Research

**Comment by bengibaykal** [comment]
Task : Issue creation and arrangement, project, milestone collaborators setup.
Duration : 1 hour
Type Of Work : Documentation

Task : 
Github repo setup.Readme updated.Wiki pages creation & arrangement.
Label creation.Github repo best practices research.
Duration: 2 hours (16.02.2020)
Type of Work: Documentation

**Comment by bengibaykal** [comment]
Task : W3C activity stream topic will be investigated and findings will be reported on wikidata.
Estimated Duration : 1 hour
Type of work : Research

**Comment by bengibaykal** [comment]
TOTAL:
Duration : 07:50
