### ISSUE TITLE
Week 7 - Jenkins Implementation Research

### ISSUE THREAD

**Issue by bengibaykal** [bengibaykal/swe574group1#49]
Research and implement Jenkins to the pipeline.
Before each merge, Jenkins tests should run without any issue.

**Comment by bengibaykal** [comment]
Here Jenkins Tutorial for Python:  [https://jenkins.io/doc/tutorials/build-a-python-app-with-pyinstaller/](url)

**Comment by bengibaykal** [comment]
1. github actions  --> python package (predefined actions will be updated.)

**Comment by bengibaykal** [comment]
Continious Implementation page created: [https://github.com/bengibaykal/swe574group1/wiki/CI-&-CD](url)

**Comment by jrqc** [comment]
Jenkins infrastructure is deployed and integrated with Project Repo
