### ISSUE TITLE
Week 1 - Research : W3C Activity Stream

### ISSUE THREAD

**Issue by bengibaykal** [bengibaykal/swe574group1#5]
Task : W3C activity stream topic will be investigated and findings will be reported on wikidata.
Estimated Duration : 3 hours
Type of work : Research
Deadline : 17.02.2020

**Comment by eermis1** [comment]
Initial research has been completed and documented in [Project Wiki](https://github.com/bengibaykal/swe574group1/wiki/4.-Research)

**Comment by eermis1** [comment]
Task : Investigate W3C Activity Stream and share the findings 
Real Duration : 1 hour
Type of work : Research
Deadline : 17.02.2020
