### ISSUE TITLE
Week 1 - Research : W3C Web Annotation Data Model

### ISSUE THREAD

**Issue by bengibaykal** [bengibaykal/swe574group1#6]
Task : W3C Web Annotation Data Model topic will be investigated and findings will be reported on wikidata.
Estimated Duration : 3 hours
Type of work : Research
Deadline : 17.02.2020

**Comment by TuracAbb** [comment]
Task : W3C Web Annotation Data Model topic will be investigated and findings will be reported on wikidata.
Real Duration : 2.5 hours
Type of work : Research
Deadline : 17.02.2020
